name: Package - MacOS
on:
  workflow_dispatch:
  workflow_call:

jobs:
  package:
    name: macOS
    runs-on: macos-14
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: brew bundle --verbose

      - name: Configure and Build
        run: |
          # I do not know why, but readline is not found by pkg-config
          # For a idea of a fix see: https://superuser.com/a/1277306
          export PKG_CONFIG_PATH=/usr/local/opt/readline/lib/pkgconfig
          # run build
          scons -j4 opengl=1 sdl2=1 macos_add_frameworks=0 macos_bundle_libs=1

      - name: Package
        run: ./contrib/packaging/macos/build_package.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos
          path: '*.zip'
